# Generated by Django 6.0.3 on 2026-05-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_customuser_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="Имя пользователя"
            ),
        ),
    ]
