# Generated by Django 6.0.3 on 2026-03-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contact_alter_product_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={
                "verbose_name": "Контактное сообщение",
                "verbose_name_plural": "Контактные сообщения",
            },
        ),
        migrations.RemoveField(
            model_name="contact",
            name="email",
        ),
        migrations.AddField(
            model_name="contact",
            name="phone",
            field=models.CharField(
                default="+7 (000) 000-00-00", max_length=20, verbose_name="Телефон"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.TextField(blank=True, verbose_name="Сообщение"),
        ),
    ]
