# Generated by Django 6.0.3 on 2026-04-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_created_at_alter_product_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyContacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100, verbose_name="Страна")),
                (
                    "tax_id",
                    models.CharField(max_length=50, verbose_name="ИНН / Tax ID"),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Адрес")),
            ],
            options={
                "verbose_name": "Реквизиты компании",
                "verbose_name_plural": "Реквизиты компании",
            },
        ),
    ]
