# Generated by Django 6.0.3 on 2026-04-01 13:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_companycontacts"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companycontacts",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Реквизиты компании",
                "verbose_name_plural": "Реквизиты компании",
            },
        ),
        migrations.AddField(
            model_name="companycontacts",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="companycontacts",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата последнего изменения"
            ),
        ),
    ]
