# Generated by Django 6.0.3 on 2026-04-13 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_companycontacts_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={
                "verbose_name": "Сообщение от пользователей",
                "verbose_name_plural": "Сообщения от пользователей",
            },
        ),
    ]
